id: amplitude_api_github
namespace: amplitude_api

triggers:
  - id: daily_trigger
    type: io.kestra.plugin.core.trigger.Schedule
    cron: "55 13 * * *"

tasks:
  - id: python_scripts
    type: io.kestra.plugin.core.flow.WorkingDirectory
    tasks:
      - id: clone_repository
        type: io.kestra.plugin.git.Clone
        url: https://github.com/ernpotter/amplitude-des3.git
        branch: main

      - id: run_python_script
        type: io.kestra.plugin.scripts.python.Commands
        taskRunner:
          type: io.kestra.plugin.scripts.runner.docker.Docker
        containerImage: python:3.11-slim
        beforeCommands:
          - pip install -r requirements.txt
        commands:
          - python main.py
        env:
          AMP_API_KEY: "{{ kv('AMP_API_KEY') }}"
          AMP_SECRET_KEY: "{{ kv('AMP_SECRET_KEY') }}"
          AWS_ACCESS_KEY: "{{ kv('AWS_ACCESS_KEY') }}"
          AWS_SECRET_KEY: "{{ kv('AWS_SECRET_KEY') }}"
          AWS_BUCKET_NAME: "{{ kv('AWS_BUCKET_NAME') }}"
          AWS_REGION_KEY: "{{ kv('AWS_REGION_KEY') }}"
